server:
  port: 8080

spring:
  datasource:
    username: root
    password: Sendy260108
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

indexing-settings:
  sites:
#    - url: https://legalxlator.com
#      name: legalxlator
#    - url: https://vodny-mall.ru
#      name: vodny-mall.ru
#    - url: https://mir-kubikov.ru
#      name: mir-kubikov.ru
#    - url: https://www.mirea.ru
#      name: mirea.ru

    - url: https://www.playback.ru/
      name: playBack.Ru
    - url: https://volochek.life/
      name: volochek.life
    - url: https://dimonvideo.ru/
      name: dimonvideo.ru


jsoup-connection:
  userAgent: ChukarinSearchBot
  referrer: http://www.google.com